server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/placement_portal
spring.datasource.username=root
spring.datasource.password=Madhuu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect